### ISSUE TITLE
NPE if e.getXref() is null

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/meta-data-action#9]
Occurs with empty bp:ID and bp:DB.

**Comment by AlexanderPico** [comment]
Ugh. Spent an hour tracking down this error again. Not really fixed?

@mkutmon Anything I can do to help debug, fix and release?

**Comment by AlexanderPico** [comment]
More details...

[failed run](https://github.com/wikipathways/wikipathways-database/actions/runs/4781883606/jobs/8517421737#step:8:497)

If the GPML contains this:
```
<bp:ID rdf:datatype="http://www.w3.org/2001/XMLSchema#string"/>
```
Then metadata action fails with an error like this:
```
org.pathvisio.libgpml.io.ConverterException: class java.lang.IllegalArgumentException: Citation must have valid xref or url, or both.
	at org.pathvisio.libgpml.model.Citation.<init>(Citation.java:60)
	at org.pathvisio.libgpml.model.PathwayElement.addCitation(PathwayElement.java:378)
	at org.pathvisio.libgpml.model.GPML2013aReader.readPublicationXrefs(GPML2013aReader.java:378)
	at org.pathvisio.libgpml.model.GPML2013aReader.readCommentGroup(GPML2013aReader.java:444)
	at org.pathvisio.libgpml.model.GPML2013aReader.readLineElement(GPML2013aReader.java:1037)
	at org.pathvisio.libgpml.model.GPML2013aReader.readInteractions(GPML2013aReader.java:944)
	at org.pathvisio.libgpml.model.GPML2013aReader.readFromRoot(GPML2013aReader.java:134)
	at org.pathvisio.libgpml.model.GPMLFormat.readFromXmlImpl(GPMLFormat.java:262)
	at org.pathvisio.libgpml.model.GPMLFormat.readFromXml(GPMLFormat.java:195)
	at org.pathvisio.libgpml.model.PathwayModel.readFromXml(PathwayModel.java:1176)
	at meta.data.action.MetaDataExtractor.main(MetaDataExtractor.java:105)
Caused by: java.lang.IllegalArgumentException: Citation must have valid xref or url, or both.
	... 11 more
```

The manual fix is to replace the line in the GPML with this:
```
<bp:ID rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NA</bp:ID>
```

**Comment by AlexanderPico** [comment]
Happened again:
https://github.com/wikipathways/wikipathways-database/actions/runs/4847863852/jobs/8638492916#step:8:100

**Comment by AlexanderPico** [comment]
I guess this is actually a libgpml bug, looking at the error log. So, different from the original issue, but popping up again in different code??

**Comment by AlexanderPico** [comment]
@egonw This could be checked in RDF generation for curation tests?

**Comment by egonw** [comment]
> This could be checked in RDF generation for curation tests?

We do have some literature references in the GPML RDF (but possibly not all, actually). But the old GPML reader only understands PubMed. ~~So, now just going to fix libGPML.~~

Already fixed in libGPML but never included in the metadata jar, it seems.

**Comment by egonw** [comment]
@AlexanderPico, I released 1.1.1 with libGPML 4.0.3 which contains the fix Tina wrote for the problem, but we never released the updated metadata action, it seems.

**Comment by egonw** [comment]
I updated the actions to use 1.1.1 and actioned a sync. All seems to have gone well. Now, we sort of need a positive control. But I need to go offline now.

**Comment by AlexanderPico** [comment]
Awesome. I can followup with some controlled test now...

**Comment by AlexanderPico** [comment]
Worked! Thanks!
